### ISSUE TITLE
Some systems failed to build for Quicklisp dist

### ISSUE THREAD

**Issue by quicklisp** [borodust/bodge-host#4]
Building with SBCL 2.1.10.195-bca540cd6 / ASDF 3.3.5 for quicklisp dist creation.

Trying to build commit id f1713d8e7badc0e0fabe0bd1cae62930087aa45e

*bodge-host* fails to build with the following error:

```
; caught WARNING:
;   * is not permitted as an argument to the FUNCTION type specifier
; 
; caught WARNING:
;   * is not permitted as an argument to the FUNCTION type specifier
...
Unhandled UIOP/LISP-BUILD:COMPILE-FILE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING {1001BFC103}>: COMPILE-FILE-ERROR while compiling #<CL-SOURCE-FILE "bodge-host" "utils">

```

[Full log here](http://report.quicklisp.org/2021-11-23/failure-report/bodge-host.html)

**Comment by borodust** [comment]
Fixed in https://github.com/borodust/bodge-utilities/commit/f888dd7f8298ebd2d563166f3564fd38245f3e07
`stable` tag for `bodge-utilties` updated.

**Comment by xach** [comment]
Sorry, but even after clearing my build caches, I still get this error.

**Comment by borodust** [comment]
Additionally, moved `bodge-host` stable tag to latest commit.

**Comment by borodust** [comment]
According to latest report, looks good.
